# Generated by Django 3.1.2 on 2020-10-10 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('driveID', models.TextField(primary_key=True, serialize=False)),
                ('secretKey', models.TextField(max_length=150)),
                ('driveName', models.TextField(max_length=150)),
                ('driveOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
