# Generated by Django 3.1.1 on 2020-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_file_sharefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharefile',
            name='shareEmails',
            field=models.EmailField(max_length=254),
        ),
    ]
