# Generated by Django 3.1.1 on 2020-10-30 04:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharefile',
            old_name='passLink',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='sharefile',
            name='secretKey',
        ),
        migrations.RemoveField(
            model_name='sharefile',
            name='share_file_name',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='otp',
            name='file_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.sharefile'),
        ),
        migrations.AddField(
            model_name='sharefile',
            name='expDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sharefile',
            name='isEncrypted',
            field=models.IntegerField(choices=[(0, 'Deny'), (1, 'Accept')], default=0),
        ),
        migrations.CreateModel(
            name='downloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseID', models.TextField()),
                ('staticCode', models.TextField()),
                ('downloader', models.TextField()),
                ('sharefileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.sharefile')),
            ],
        ),
    ]
