# Generated by Django 3.1.1 on 2020-10-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201030_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadfile',
            old_name='sharefileID',
            new_name='sharefile',
        ),
    ]
