# Generated by Django 3.1.1 on 2020-10-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201030_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='share_file_name',
            field=models.TextField(default=''),
        ),
    ]
