# Generated by Django 3.1.1 on 2020-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_sharefile_share_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadfile',
            old_name='staticCode',
            new_name='fileID_zip',
        ),
        migrations.RemoveField(
            model_name='downloadfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='licenseID',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
