# Generated by Django 3.1.1 on 2020-11-04 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_sharefile_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
