# Generated by Django 3.1.1 on 2020-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_downloadfile_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='downloadable',
            field=models.IntegerField(choices=[(0, 'Deny'), (1, 'Accept')], default=0),
        ),
    ]
