# Generated by Django 3.1.1 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_sharefile_downloadable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharefile',
            name='expDate',
            field=models.DateTimeField(),
        ),
    ]
