# Generated by Django 3.1.1 on 2020-11-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20201109_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharefile',
            name='isEncrypted',
        ),
    ]
