# Generated by Django 3.1.1 on 2020-11-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_sharefile_isencrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='secretKey',
        ),
    ]
