# Generated by Django 3.1.1 on 2020-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201121_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharefile',
            name='shareEmails',
            field=models.EmailField(max_length=254),
        ),
    ]
